// profile sce_vp_psp2

uniform float4x4 uMvpMatrix;

void main(
    float2 inVertexPosition,
    float4 inVertexColor,
    float2 inTexCoord0,
    float2 out varTexCoord0 : TEXCOORD,
    float4 out varColor : COLOR,
    float4 out gl_Position : POSITION
){
    varColor     = inVertexColor/255.1;
    varTexCoord0 = inTexCoord0;
    gl_Position  = mul(float4(inVertexPosition, 0.0, 1.0), uMvpMatrix);
}
