// profile sce_fp_psp2

uniform float g_LODBias;
uniform sampler2D g_Texture0;

float4 main(
    float2 TexCoord0 : TEXCOORD0,
    float4 UniformCol : COLOR,
    float FogFactor : TEXCOORD5,
    float4 FogFactorColor : TEXCOORD6
) {
    float4 temporary;
    temporary = (tex2Dbias(g_Texture0, float4(TexCoord0, 1.0, g_LODBias)) * UniformCol);
    return float4(((temporary.xyz * FogFactor) + FogFactorColor.xyz), temporary.a);
}
